import React, { useState, useEffect } from 'react';
import { Box, Typography, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Button, Dialog, DialogTitle, DialogContent, DialogActions, Chip, Divider, Grid } from '@mui/material';
import api from '../api';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

function RunHistory() {
    const [runs, setRuns] = useState([]);
    const [selectedRun, setSelectedRun] = useState(null);
    const [open, setOpen] = useState(false);

    const fetchHistory = async () => {
        try {
            const res = await api.get('/execute/history');
            setRuns(res.data);
        } catch (err) {
            console.error('Failed to fetch history', err);
        }
    };

    const viewDetails = async (id) => {
        try {
            const res = await api.get(`/execute/history/${id}`);
            setSelectedRun(res.data);
            setOpen(true);
        } catch (err) {
            console.error('Failed to fetch details', err);
        }
    };

    const exportToCSV = () => {
        if (!selectedRun) return;

        const headers = ["Order", "Test Name", "Status", "Duration (ms)"];
        const rows = selectedRun.results.map(r => [
            r.orderIndex,
            r.testName,
            r.status.toUpperCase(),
            r.duration
        ]);

        const csvContent = [
            `Report: AutoTestX Execution Summary`,
            `Run ID: ${selectedRun._id}`,
            `Date: ${new Date(selectedRun.runAt).toLocaleString()}`,
            `Execution Mode: ${selectedRun.executionMode}`,
            `Runner Type: ${selectedRun.runnerType || 'local'}`,
            `Summary: ${selectedRun.passedCount} Passed, ${selectedRun.failedCount} Failed, Total: ${selectedRun.duration}ms`,
            "",
            headers.join(","),
            ...rows.map(row => row.join(","))
        ].join("\n");

        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement("a");
        const url = URL.createObjectURL(blob);
        link.setAttribute("href", url);
        link.setAttribute("download", `AutoTestX_Report_${selectedRun._id.substring(0, 8)}.csv`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const exportToPDF = () => {
        if (!selectedRun) return;

        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.text("AutoTestX Execution Report", 14, 20);

        doc.setFontSize(12);
        doc.setTextColor(100);
        doc.text(`Run ID: ${selectedRun._id.toUpperCase()}`, 14, 30);
        doc.text(`Date / Time: ${new Date(selectedRun.runAt).toLocaleString()}`, 14, 37);

        // Summary Metadata
        doc.setTextColor(0);
        doc.setFontSize(14);
        doc.text("Execution Summary", 14, 50);

        doc.setFontSize(11);
        const metaY = 57;
        doc.text(`Execution Mode: ${selectedRun.executionMode}`, 14, metaY);
        doc.text(`Runner Type: ${selectedRun.runnerType?.toUpperCase() || 'LOCAL'}`, 14, metaY + 7);
        doc.text(`Efficiency Optimization: AI-Prioritized Order`, 14, metaY + 14);

        // Stats
        doc.setFontSize(11);
        doc.text(`Results: ${selectedRun.passedCount} Passed, ${selectedRun.failedCount} Failed`, 14, metaY + 25);
        doc.text(`Total Execution Duration: ${selectedRun.duration} ms`, 14, metaY + 32);

        // Results Table
        autoTable(doc, {
            startY: metaY + 40,
            head: [['#', 'Test Case Name', 'Status', 'Duration (ms)']],
            body: selectedRun.results.map(r => [
                r.orderIndex,
                r.testName,
                r.status.toUpperCase(),
                r.duration
            ]),
            headStyles: { fillStyle: 'bold', fillColor: [33, 150, 243] },
            alternateRowStyles: { fillColor: [245, 245, 245] },
            margin: { top: 20 }
        });

        // Footer
        const finalY = doc.lastAutoTable?.finalY || 200;
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by AutoTestX Intelligent Testing Platform", 14, finalY + 20);

        doc.save(`AutoTestX_Report_${selectedRun._id.substring(0, 8)}.pdf`);
    };

    useEffect(() => {
        fetchHistory();
    }, []);

    return (
        <Box sx={{ p: 4 }}>
            <Typography variant="h4" sx={{ fontWeight: 'bold', mb: 3 }}>
                Run History
            </Typography>
            <TableContainer component={Paper} elevation={3} sx={{ borderRadius: 2 }}>
                <Table>
                    <TableHead sx={{ bgcolor: 'background.default' }}>
                        <TableRow>
                            <TableCell sx={{ fontWeight: 'bold' }}>Run ID</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Date / Time</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Status</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Total Tests</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Passed / Failed</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Duration (ms)</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Mode</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Runner</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Actions</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {runs.map(run => {
                            const failureRate = run.totalTests > 0 ? (run.failedCount / run.totalTests) : 0;
                            let statusColor = 'error';
                            let statusLabel = 'Critical';

                            if (run.failedCount === 0) {
                                statusColor = 'success';
                                statusLabel = 'Perfect';
                            } else if (failureRate < 0.3) {
                                statusColor = 'warning';
                                statusLabel = 'Stable';
                            }

                            return (
                                <TableRow key={run._id} hover>
                                    <TableCell sx={{ fontSize: '0.75rem', fontFamily: 'monospace' }}>
                                        {run._id.substring(run._id.length - 8).toUpperCase()}
                                    </TableCell>
                                    <TableCell>{new Date(run.runAt).toLocaleString()}</TableCell>
                                    <TableCell>
                                        <Chip
                                            label={statusLabel}
                                            size="small"
                                            color={statusColor}
                                            sx={{ fontWeight: 'bold', minWidth: '70px' }}
                                        />
                                    </TableCell>
                                    <TableCell>{run.totalTests}</TableCell>
                                    <TableCell>
                                        <Box sx={{ display: 'flex', gap: 1 }}>
                                            <Typography sx={{ color: 'success.main', fontWeight: 'bold' }}>{run.passedCount} P</Typography>
                                            <Typography sx={{ color: 'error.main', fontWeight: 'bold' }}>{run.failedCount} F</Typography>
                                        </Box>
                                    </TableCell>
                                    <TableCell>{run.duration}</TableCell>
                                    <TableCell>
                                        <Chip
                                            label={run.executionMode || 'Standard'}
                                            size="small"
                                            color="secondary"
                                            variant="outlined"
                                        />
                                    </TableCell>
                                    <TableCell>
                                        <Chip
                                            label={run.runnerType?.toUpperCase() || 'LOCAL'}
                                            size="small"
                                            color={run.runnerType === 'docker' ? 'info' : 'default'}
                                            sx={{ fontWeight: 'bold' }}
                                        />
                                    </TableCell>
                                    <TableCell>
                                        <Button variant="contained" size="small" onClick={() => viewDetails(run._id)} sx={{ textTransform: 'none' }}>
                                            Details
                                        </Button>
                                    </TableCell>
                                </TableRow>
                            );
                        })}
                    </TableBody>
                </Table>
            </TableContainer>

            <Dialog open={open} onClose={() => setOpen(false)} maxWidth="md" fullWidth>
                <DialogTitle sx={{ borderBottom: '1px solid', borderColor: 'divider', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Typography variant="h6">Run Details & Logs</Typography>
                    <Box>
                        <Button size="small" variant="outlined" sx={{ mr: 1 }} onClick={exportToCSV}>Export CSV</Button>
                        <Button size="small" variant="contained" color="primary" onClick={exportToPDF}>Export PDF</Button>
                    </Box>
                </DialogTitle>
                <DialogContent dividers sx={{ bgcolor: '#f8f9fa' }}>
                    {selectedRun && (
                        <Box>
                            <Grid container spacing={2} sx={{ mb: 3 }}>
                                <Grid item xs={12} sm={6}>
                                    <Paper sx={{ p: 2 }}>
                                        <Typography variant="caption" color="textSecondary" display="block">METADATA</Typography>
                                        <Typography variant="body2"><strong>Execution:</strong> {new Date(selectedRun.runAt).toLocaleString()}</Typography>
                                        <Typography variant="body2"><strong>Mode:</strong> {selectedRun.executionMode}</Typography>
                                        <Typography variant="body2"><strong>Runner:</strong> {selectedRun.runnerType?.toUpperCase() || 'LOCAL'}</Typography>
                                        {selectedRun.branch && <Typography variant="body2"><strong>Branch:</strong> {selectedRun.branch}</Typography>}
                                        {selectedRun.commitId && (
                                            <Typography variant="body2">
                                                <strong>Commit:</strong> <span style={{ fontFamily: 'monospace' }}>{selectedRun.commitId.substring(0, 7)}</span>
                                            </Typography>
                                        )}
                                    </Paper>
                                </Grid>
                                <Grid item xs={12} sm={6}>
                                    <Paper sx={{ p: 2, bgcolor: 'primary.main', color: 'white' }}>
                                        <Typography variant="caption" sx={{ opacity: 0.8 }} display="block">PERFORMANCE</Typography>
                                        <Typography variant="h5" sx={{ fontWeight: 'bold' }}>{selectedRun.duration}ms</Typography>
                                        <Typography variant="body2">{selectedRun.passedCount} Passed | {selectedRun.failedCount} Failed</Typography>
                                    </Paper>
                                </Grid>
                            </Grid>

                            <Typography variant="h6" sx={{ mb: 2, fontSize: '1rem' }}>AI-Prioritized Execution Order</Typography>
                            <Box sx={{ mt: 2 }}>
                                {selectedRun.results.map((res, idx) => (
                                    <Paper key={idx} sx={{ p: 2, mb: 2, borderLeft: `6px solid ${res.status === 'passed' ? '#4caf50' : '#f44336'}` }} elevation={1}>
                                        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                                            <Typography variant="body1" sx={{ fontWeight: 'bold' }}>
                                                {res.orderIndex}. {res.testName}
                                            </Typography>
                                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                                                <Typography variant="body2" sx={{ color: res.status === 'passed' ? 'success.main' : 'error.main', fontWeight: 'bold', fontSize: '0.8rem' }}>
                                                    {res.status.toUpperCase()}
                                                </Typography>
                                                <Typography variant="caption" color="textSecondary">
                                                    ({res.duration || 0}ms)
                                                </Typography>
                                            </Box>
                                        </Box>
                                        <Box
                                            component="pre"
                                            sx={{
                                                mt: 1,
                                                p: 1.5,
                                                bgcolor: '#0d1117',
                                                color: '#c9d1d9',
                                                borderRadius: 1,
                                                whiteSpace: 'pre-wrap',
                                                fontFamily: 'monospace',
                                                fontSize: '0.7rem',
                                                maxHeight: '120px',
                                                overflowY: 'auto',
                                                border: '1px solid #30363d'
                                            }}
                                        >
                                            {res.logs}
                                        </Box>
                                    </Paper>
                                ))}
                            </Box>
                        </Box>
                    )}
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setOpen(false)}>Close</Button>
                </DialogActions>
            </Dialog>
        </Box>
    );
}

export default RunHistory;
